spring:
  datasource:
    password: {cipher}8f317371241250fe0376d3838e653764a7161649364f4ed9aec0f58735f2fd87
    url: jdbc:mysql://localhost:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: beer_service
  artemis:
    user: artemis
    password: {cipher}ff879ec0e65a9aabfdf51fe90b7f9138d91176c1590004179adbbe1ab5a247aa